#!/bin/sh

### BEGIN INIT INFO
# Provides: ros_earth_rover
# Required-Start: $network
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: ensure ros daemons are started (nmbd and smbd)
### END INIT INFO

case $1 in
     start)
       # Launch ros script with screen 
       su - earth -c "screen -dmS ros -c /home/earth/catkin_ws/src/earth-rover-ros/scripts/.roslaunch.rc -t ros_main bash --rcfile .bashrc -ci /home/earth/catkin_ws/src/earth-rover-ros/scripts/launch_all.sh"
       ;;
     stop)
        kill -s 15 `pidof screen`
        ;;
esac
exit 0

